services:

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mariadb:11.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Afpa1234
      MYSQL_DATABASE: village_green_fr
      MYSQL_USER: admin
      MYSQL_PASSWORD: Marc2003.
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
